COUNTRY_NAMES_LIST = [
    'AGO Angola',
    'BEN Bénin',
    'BFA Burkina Faso',
    'CAF Centrafrique',
    'CIV Côte d_Ivoire',
    'CMR Cameroun',
    'COD RDC',
    'COG Congo',
    'GAB Gabon',
    'GIN Guinée (Conakry)',
    'Ghana',
    'KEN Kenya',
    'LBR Liberia',
    'MDG Madagascar',
    'MLI Mali',
    'MRT Mauritanie',
    'NER Niger',
    'NGA Nigeria',
    'SEN Sénégal',
    'SLE Sierra Leone',
    'TCD Tchad',
    'TZA Tanzanie',
    'ZAF Afrique du Sud',
    'ZWE Zimbabwe'
]